include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - lib/core/config/injectable_config.config.dart
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
  errors:
    invalid_annotation_target: ignore
    missing_required_param: error
    missing_return: error

linter:
  rules:
    # Style
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_locals: false
    use_super_parameters: true
    sized_box_for_whitespace: true
    avoid_unnecessary_containers: true
    
    # Documentation
    public_member_api_docs: false
    
    # Safety
    avoid_print: true
    avoid_dynamic_calls: false
    always_declare_return_types: true
    
    # Disabled
    lines_longer_than_80_chars: false
    sort_child_properties_last: false
